baseURL = "https://haleuan.github.io/"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
theme = "PaperMod"
paginate = 7

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = false
minifyOutput = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Haleuan"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
description = "ExampleSite description"
env = "production"
keywords = ["Blog", "Haleuan"]
math = true
ShowCodeCopyButtons = true
ShowTaxonomies = true
ShowCategories = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/Haleuan"

[params.assets]
disableHLJS = true
favicon = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
favicon16x16 = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
favicon32x32 = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
apple_touch_icon = "assets/jupiter_favicon/jupiter_planet_icon_128.png"
safari_pinned_tab = "assets/jupiter_favicon/jupiter_planet_icon_256.png"

[params.profileMode]
enabled = false
title = "ExampleSite"
imageWidth = 120

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

[taxonomies]
category = "categories"
tag = "tags"

[languages.zh-cn]
label = "中文"
weight = 1
title = "Haleuan's Blog"

[languages.zh-cn.params.homeInfoParams]
Title = "This is Haleuan's Neverland"
Content = '''
Gatsby believed in the green light, the orgastic future that year by year recedes89 before us. It eluded90 us then, but that's no matter--tomorrow we will run faster, stretch out our arms farther.... And one fine morning.

So we beat on, boats against the current, borne back ceaselessly into the past.'''

[[languages.zh-cn.menu.main]]
identifier = "archive"
name = "归档"
url = "/archives"
weight = 10

[[languages.zh-cn.menu.main]]
identifier = "categories"
name = "分类"
url = "/categories"
weight = 20

[[languages.zh-cn.menu.main]]
identifier = "tags"
name = "标签"
url = "/tags"
weight = 30

[[languages.zh-cn.menu.main]]
identifier = "search"
name = "搜索"
url = "/search"
weight = 40

[languages.en]
label = "English"
weight = 2
title = "Haleuan's Blog"

[languages.en.params.homeInfoParams]
Title = "This is Haleuan's Neverland"
Content = '''
Gatsby believed in the green light, the orgastic future that year by
year recedes before us. It eluded us then, but that's no matter--tomorrow
we will run faster, stretch out our arms farther....

And one fine morning. So we beat on, boats against the current, borne back ceaselessly into the past.'''

[[languages.en.menu.main]]
identifier = "archive"
name = "Archives"
url = "/archives"
weight = 10

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = 20

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 40

[markup.highlight]
noClasses = false
style = "monokai"
codeFences = true
lineNos = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [
  ['\[', '\]'],
  ['$$', '$$']
]
inline = [
  ['\(', '\)'],
  ['$', '$']
]
