baseURL = 'https://arcolaus.github.io'
languageCode = 'zh-cn'
title = 'Arcolaus'
theme = "PaperMod"

[params]
defaultTheme = "dark"
math = true

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my website."

[[params.socialIcons]]
name = "email"
url = ""

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
favicon16x16 = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
favicon32x32 = "assets/jupiter_favicon/jupiter_planet_icon_32.png"
apple_touch_icon = "assets/jupiter_favicon/jupiter_planet_icon_128.png"
safari_pinned_tab = "assets/jupiter_favicon/jupiter_planet_icon_256.png"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[[markup.goldmark.extensions.passthrough.delimiters.block]]
opener = "\\["
closer = "\\]"

[[markup.goldmark.extensions.passthrough.delimiters.block]]
opener = "$$"
closer = "$$"

[[markup.goldmark.extensions.passthrough.delimiters.inline]]
opener = "\\("
closer = "\\)"

[[markup.goldmark.extensions.passthrough.delimiters.inline]]
opener = "$"
closer = "$"